name: Validate Composer Files
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  validate-composer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Validate composer.json
      run: composer validate --no-check-all --strict

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    - name: Validate composer.lock
      run: composer validate --no-check-all --strict --no-interaction --with-dependencies
